/** @format */

const actionTypes = Object.freeze({
      //app
      APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
      SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",
      CHANGE_LANGUAGE: "CHANGE_LANGUAGE",

      //admin
      // ADMIN_LOGIN_SUCCESS: 'ADMIN_LOGIN_SUCCESS',
      // ADMIN_LOGIN_FAIL: 'ADMIN_LOGIN_FAIL',
      // PROCESS_LOGOUT: 'PROCESS_LOGOUT',

      //user
      ADD_USER_SUCCESS: "ADD_USER_SUCCESS",
      USER_LOGIN_SUCCESS: "USER_LOGIN_SUCCESS",
      USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
      PROCESS_LOGOUT: "PROCESS_LOGOUT",
      //SAVE USER
      CREATE_USER_START: "CREATE_USER_START",
      CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
      CREATE_USER_FAILED: "CREATE_USER_FAILED",
      //GET ALL INFO USER
      FETCH_ALL_USER_START: "FETCH_ALL_USER_START",
      FETCH_ALL_USER_SUCCESS: "FETCH_ALL_USER_SUCCESS",
      FETCH_ALL_USER_FAILED: "FETCH_ALL_USER_FAILED",

      //DELETE USER WITH ID
      DELETE_USER_START: "DELETE_USER_START",
      DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
      DELETE_USER_FAILED: "DELETE_USER_FAILED",

      // UPDATE USER
      UPDATE_USER_START: "UPDATE_USER_START",
      UPDATE_USER_SUCCESS: "UPDATE_USER_SUCCESS",
      UPDATE_USER_FAILED: "UPDATE_USER_FAILED",
      //GENDERS

      // ACTION TYPE OF SHOP
      //CREATE ITEM PRODUCT
      CREATE_ITEM_PRODUCT_START: "CREATE_ITEM_PRODUCT_START",
      CREATE_ITEM_PRODUCT_SUCCESS: "CREATE_ITEM_PRODUCT_SUCCESS",
      CREATE_ITEM_PRODUCT_FAILED: "CREATE_ITEM_PRODUCT_FAILED",

      // FETCH ALL PRODUCT ITEM BY SHOP
      FETCH_ALL_ITEM_PRODUCT_START: "FETCH_ALL_ITEM_PRODUCT_START",
      FETCH_ALL_ITEM_PRODUCT_SUCCESS: "FETCH_ALL_ITEM_PRODUCT_SUCCESS",
      FETCH_ALL_ITEM_PRODUCT_FAILED: "FETCH_ALL_ITEM_PRODUCT_FAILED",
      //DELETE ITEM PRODUCT WITH ID PRODUCT
      DELETE_PRODUCT_START: "DELETE_PRODUCT_START",
      DELETE_PRODUCT_SUCCESS: "DELETE_PRODUCT_SUCCESS",
      DELETE_PRODUCT_FAILED: "DELETE_PRODUCT_FAILED",
      // UPDATE ITEM PRODUCT WITH ID
      UPDATE_PRODUCT_START: "UPDATE_PRODUCT_START",
      UPDATE_PRODUCT_SUCCESS: "UPDATE_PRODUCT_SUCCESS",
      UPDATE_PRODUCT_FAILED: "UPDATE_PRODUCT_FAILED",

      // ACTION TYPE OF BUYER
      FETCH_ALL_ITEM_PRODUCT_BY_BUYER_START: "FETCH_ALL_ITEM_PRODUCT_BY_BUYER_START",
      FETCH_ALL_ITEM_PRODUCT_BY_BUYER_SUCCESS: "FETCH_ALL_ITEM_PRODUCT_BY_BUYER_SUCCESS",
      FETCH_ALL_ITEM_PRODUCT_BY_BUYER_FAILED: "FETCH_ALL_ITEM_PRODUCT_BY_BUYER_FAILED",
      // BUYER ADD ITEM FOOD TO CART ITEM
      //fetchAddFoodToCart
      FETCH_ADD_FOOD_TO_CART_START: "FETCH_ADD_FOOD_TO_CART_START",
      FETCH_ADD_FOOD_TO_CART_SUCCESS: "FETCH_ADD_FOOD_TO_CART_SUCCESS",
      FETCH_ADD_FOOD_TO_CART_FAILED: "FETCH_ADD_FOOD_TO_CART_FAILED",

      //get all cart buyer
      FETCH_ALL_CART_START: "FETCH_ALL_CART_START",
      FETCH_ALL_CART_SUCCESS: "FETCH_ALL_CART_SUCCESS",
      FETCH_ALL_CART_FAILED: "FETCH_ALL_CART_FAILED",
});

export default actionTypes;
